### ISSUE TITLE
Tried migration using Docker container but didn't work

### ISSUE THREAD

**Issue by surapuramakhil** [techouse/sqlite3-to-mysql#102]
**Describe the bug**
find output

```sh

Unable to find image 'ghcr.io/techouse/sqlite3-to-mysql:latest' locally
latest: Pulling from techouse/sqlite3-to-mysql
661ff4d9561e: Already exists
44cda88cd45d: Pull complete
8d184ace8e99: Pull complete
fbcb6e47dc5d: Pull complete
8dc42379c8ec: Pull complete
f5da05dee4b9: Pull complete
Digest: sha256:dd9c087f4231979f2392a5b83242ef57c1075bb00dcdd18be5c1253bad113967
Status: Downloaded newer image for ghcr.io/techouse/sqlite3-to-mysql:latest
2024-02-15 13:23:28 ERROR    2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)
2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)

```

that's end output.

**Expected behaviour**
What you expected.

**Actual result**
What happened instead.

**System Information**

```bash
$ sqlite3mysql --version
```

```
<paste here>
```

This command is only available on v1.3.6 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by techouse** [comment]
Hey,

How did you mount/expose your database to the docker image?

Have you followed the instructions here https://github.com/techouse/sqlite3-to-mysql?tab=readme-ov-file#docker ?

**Comment by techouse** [comment]
Hmm, looks like this is a [known issue](https://stackoverflow.com/questions/70653019/mysql-error2003-cant-connect-to-mysql-server-on-100su-docker) and has to do with the fact that the hostname has the port in it. Could you try passing the port separately?

**Comment by surapuramakhil** [comment]
I am running mysql on its default port 3306. can you share instructions or parameter that I can use for passing port to the image

**Comment by techouse** [comment]
Try using this switch
`-P, --mysql-port INTEGER        MySQL port. Defaults to 3306.`

**Comment by surapuramakhil** [comment]
Hey @techouse , I have tried adding port. its still the same

```sh
docker run -it \
    --workdir $(pwd) \
    --volume $(pwd):$(pwd) \
    --rm ghcr.io/techouse/sqlite3-to-mysql:latest \
    --sqlite-file ***** \
    --mysql-user ****** \
    --mysql-password ***** \
    --mysql-database ***** \
    --mysql-host host.docker.internal \
    --mysql-port 3306
2024-02-19 22:26:52 ERROR    2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)
2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)

```

**Comment by surapuramakhil** [comment]
Even I tried with -P its still same

```sh
 docker run -it     --workdir $(pwd)     --volume $(pwd):$(pwd)     --rm ghcr.io/techouse/sqlite3-to-mysql:latest     --sqlite-file ****     --mysql-user ******     --mysql-password ******     --mysql-database ******     --mysql-host host.docker.internal     -P 3306
2024-02-19 22:27:34 ERROR    2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)
2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a real number is required, not str)

```

**Comment by surapuramakhil** [comment]
python tool worked. I have did migration using python. but docker version didn't work

**Comment by techouse** [comment]
Hey @surapuramakhil 

I just tried it on macOS 14.3.1 running Docker v25.0.3 and MySQL v8.2.0 running on locally on port 3306 and it worked just fine porting [this example database](https://github.com/ivanceras/sakila/blob/master/sqlite-sakila-db/sakila.db) using the exact command as in the readme

```bash
docker run -it \
    --workdir $(pwd) \
    --volume $(pwd):$(pwd) \
    --rm ghcr.io/techouse/sqlite3-to-mysql:latest \
    --sqlite-file sakila.db \
    --mysql-user foo \
    --mysql-password bar \
    --mysql-database sakila \
    --mysql-host host.docker.internal
```

**Comment by techouse** [comment]
> but docker version didn't work

So I gather your Docker setup is misconfigured?

**Comment by surapuramakhil** [comment]
I am running it on Linux - Ubuntu 22. Even I have close docker version - 25.0.1

you can also check the commands i have ran along with its output.

**Comment by techouse** [comment]
Hey,

I simply can'r reproduce it with any demo SQLite db.

Could you maybe send me a snippet of your SQLite database? Maybe it holds some clues.

**Comment by surapuramakhil** [comment]
Yeah Sure. its an open source project. Apache Answer https://github.com/apache/incubator-answer

I have initially started with project using sqlite. Now migrating it to mysql

**Comment by techouse** [comment]
I'm sorry, maybe I wasn't clear enough. I need a sample of *your* database that is problematic, otherwise I can not help you.
