### ISSUE TITLE
Data Migration with incorrect values when values are out of data range instead of an error.

### ISSUE THREAD

**Issue by surapuramakhil** [techouse/sqlite3-to-mysql#104]
**Describe the bug**

range of int in MYSQL - -2147483648 to 2147483647
range of int in Sqlite - -9223372036854775808 to +9223372036854775807

Value in source DB - 10010000000000001
got value in target mysql db - 2147483647  instead of receiving an error asking me to correct

**Expected behaviour**
receiving an error asking me to correct (or) it should choose correct data type which can store that value

**Actual result**
got value in target mysql db - 2147483647

**System Information**

```bash
$ sqlite3mysql --version
```

```
| software               | version                                                           |
|------------------------|-------------------------------------------------------------------|
| sqlite3-to-mysql       | 2.1.7                                                             |
|                        |                                                                   |
| Operating System       | Linux 5.15.0-1037-kvm                                             |
| Python                 | CPython 3.10.12                                                   |
| MySQL                  | mysql  Ver 8.0.33-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu)) |
| SQLite                 | 3.37.2                                                            |
|                        |                                                                   |
| click                  | 8.1.7                                                             |
| mysql-connector-python | 8.3.0                                                             |
| pytimeparse2           | 1.7.1                                                             |
| simplejson             | 3.19.2                                                            |
| tabulate               | 0.9.0                                                             |
| tqdm                   | 4.66.2                                                            |
```

This command is only available on v1.3.6 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by surapuramakhil** [comment]
even tested with debug mode. No errors are thrown

**Comment by techouse** [comment]
The databases handle these datatypes differently and it was never my intention to handle every edge case (like this one) with the tool.

You have 2 options.

1. Use the switch `--mysql-integer-type="BIGINT (19)" to override the default integer data type
2. Manually create the DDL in MySQL and then migrate

**Comment by surapuramakhil** [comment]
Can you share instructions on how to perform 2nd Option. I tried that code stated messing with schema of I have raised https://github.com/techouse/sqlite3-to-mysql/issues/105

**Comment by techouse** [comment]
> Can you share instructions on how to perform 2nd Option. I tried that. code stated messing with schema So I have raised #105

I strongly suggest option 1.

**Comment by surapuramakhil** [comment]
> > Can you share instructions on how to perform 2nd Option. I tried that. code stated messing with schema So I have raised #105
> 
> I strongly suggest option 1.

Ah it is not just one column time there are other columns types which got effected. Number is around 6+

So that's why I have asked for 2

**Comment by techouse** [comment]
That flag will take care of the datatype, regardless of how many columns there are.

**Comment by surapuramakhil** [comment]
Ah you didn't get what I said its **column types not column names**. bug is filed for integer column type, there are other columns which were also effected like timestamp columns and text columns

**Comment by techouse** [comment]
> there are other columns which were also effected like timestamp columns and text columns

Please provide concrete examples with which I can replicate these issues that you are facing.
