### ISSUE TITLE
Tool is messing with schema in auto increment

### ISSUE THREAD

**Issue by surapuramakhil** [techouse/sqlite3-to-mysql#106]
**Describe the bug**
For few random tables tool has added auto increment values some tables with value 4, sometable with value 2  and for some tables didn't add and auto increment  

**Expected behaviour**
What you expected.

**Actual result**
What happened instead.

**System Information**

```bash
$ sqlite3mysql --version
```

```
<paste here>
```

This command is only available on v1.3.6 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by techouse** [comment]
Can you please provide a database with which I can replicate the error?
