### ISSUE TITLE
It displayed problem when I attempted to migrate data from SQLite to MySQL.

### ISSUE THREAD

**Issue by krupesh1958** [techouse/sqlite3-to-mysql#108]
`Mysql Version:- 8.0`

Error:
```
mysql.connector.errors.DatabaseError: 3780 (HY000): Referencing column 'user_activity_id' and referenced column 'id' in foreign key constraint 'common_app_notification_FK_0_0' are incompatible.
```

**Comment by techouse** [comment]
Hi,

I'll need a bit more info to help you out here.

You can start by supplying the DDL and some sample data.

**Comment by techouse** [comment]
> Can you please explain me bit more about Without transferring foreign key.

As the manual / help text says, you use the tool with this switch
```
-X, --without-foreign-keys      Do not transfer foreign keys.
```

> How it's work and how my problem will solve within this?

You'll then have to use some DBA tool, like say DBeaver, and update your foreign keys in your MySQL database manually.
