### ISSUE TITLE
DATE field contains Invalid isoformat string: '2024-05-21 00:00:00'

### ISSUE THREAD

**Issue by zimbar** [techouse/sqlite3-to-mysql#120]
**Describe the bug**
I want to convert a sqlite db to mysql

**Actual result**

Error: DATE field contains Invalid isoformat string: '2024-05-21 00:00:00' when transfering table

**System Information**

```bash
$ sqlite3mysql --version
```
| software               | version                                                                             |
|------------------------|-------------------------------------------------------------------------------------|
| sqlite3-to-mysql       | 2.2.0                                                                               |
|                        |                                                                                     |
| Operating System       | Linux 6.9.8-200.fc40.x86_64                                                         |
| Python                 | CPython 3.12.4                                                                      |
| MySQL                  | mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using  EditLine wrapper |
| SQLite                 | 3.45.1                                                                              |
|                        |                                                                                     |
| click                  | 8.1.7                                                                               |
| mysql-connector-python | 9.0.0                                                                               |
| pytimeparse2           | 1.7.1                                                                               |
| simplejson             | 3.19.2                                                                              |
| tabulate               | 0.9.0                                                                               |
| tqdm                   | 4.66.4                       

```
**System** : Fedora 40
**Python** 3.12.4

**The error with --debug**:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlite3_to_mysql/sqlite_utils.py", line 44, in convert_date
    return date.fromisoformat(value.decode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: '2024-05-21 00:00:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqlite3mysql", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlite3_to_mysql/cli.py", line 202, in cli
    ).transfer()
      ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlite3_to_mysql/transporter.py", line 741, in transfer
    self._transfer_table_data(sql=sql, total_records=total_records)
  File "/usr/local/lib/python3.12/site-packages/sqlite3_to_mysql/transporter.py", line 646, in _transfer_table_data
    self._sqlite_cur.fetchall(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlite3_to_mysql/sqlite_utils.py", line 46, in convert_date
    raise ValueError(f"DATE field contains {err}")  # pylint: disable=W0707
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: DATE field contains Invalid isoformat string: '2024-05-21 00:00:00'


Thanks

**Comment by techouse** [comment]
Can you please fill out the bug report form, thanks!

**Comment by techouse** [comment]
Looks like that's not an ISO format that Python expects https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat

I'll look into it.

P.S.: There were some changes in Python 3.11 it seems. Could you try and run this with Python 3.10?

**Comment by techouse** [comment]
> I don't have python 3.10 installed

https://github.com/pyenv/pyenv

**Comment by techouse** [comment]
Finally found some time to get to the bottom of this.

The issue is that this expects a `date` and not a `datetime`, which means that:
```python
from datetime import date

print(date.fromisoformat('2024-05-21'))
```
will work, however,
```python
from datetime import date

print(date.fromisoformat('2024-05-21 00:00:00'))
```
will not work as it is a `datetime`, not a `date`.

CC / @zimbar

**Comment by techouse** [comment]
@zimbar this has been fixed in #121 and is due to be released in v2.2.1

**Comment by zimbar** [comment]
@techouse
 
It works.

Thanks

**Comment by techouse** [comment]
@zimbar Great, however, your data is still incorrect.
