### ISSUE TITLE
password prompt

### ISSUE THREAD

**Issue by elig0n** [techouse/sqlite3-to-mysql#16]
**Is your feature request related to a problem? Please describe.**
passing a plaintext password over command line is insecure

**Describe the solution you'd like**
password prompt with hidden/asterisks input

**Describe alternatives you've considered**
keychain

**Comment by techouse** [comment]
I never really paid much attention to this since the password option is optional and well since this tool is more or less a one-time-use thing for most people, but you do have a point. I'll look into it.
