### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by elig0n** [techouse/sqlite3-to-mysql#17]
**Is your feature request related to a problem? Please describe.**
when going over a large database a progress indicator can be very useful i.e. that everything is performing well, how much is done, how much is left etc...

**Describe the solution you'd like**
a progress bar, either records done, left, megabytes written ... whatever

**Describe alternatives you've considered**
`du` the database directory repeatedly, i.e. to see space usage

**Comment by techouse** [comment]
Not sure if I want to add more complexity to it, to be honest. Will think about it.
