### ISSUE TITLE
Access Denied for user

### ISSUE THREAD

**Issue by Kuntish** [techouse/sqlite3-to-mysql#19]
**Describe the bug**
Can't connect to remote mysql host, access denied for user even though I can connect using the mysql CLI tool

**System Information**
| software               | version                                                           |
|------------------------|-------------------------------------------------------------------|
| sqlite3-to-mysql       | 1.3.12                                                            |
|                        |                                                                   |
| Operating System       | Linux 4.19.128-microsoft-standard                                 |
| Python                 | CPython 3.8.5                                                     |
| MySQL                  | mysql  Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu)) |
| SQLite                 | 3.31.1                                                            |
|                        |                                                                   |
| click                  | 7.0                                                               |
| mysql-connector-python | 8.0.23                                                            |
| pytimeparse            | 1.1.8                                                             |
| simplejson             | 3.16.0                                                            |
| six                    | 1.14.0                                                            |
| tabulate               | 0.8.9                                                             |
| tqdm                   | 4.60.0                                                            |

**Additional context**
I am pretty sure this is due to the script using TLS whilst my host does not use it, and there being no option to turn it off

**Comment by techouse** [comment]
So this uses the Python MySQL Connector to connect to the database and as you can see in [the official documentation](https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html) the option
```
ssl_disabled=False
```
is disabled by default.

I'll add a feature switch to set this to true if desired.
