### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by Ulixestoitaca** [techouse/sqlite3-to-mysql#2]
Hello,

I am geting this error OverflowError: Python int too large to convert to C long when moving data to mysql. Is there anything I can do?

**Comment by techouse** [comment]
From the top of my head I might think to use a string or something like NumPy's `np.int64`. Can you maybe provide s sample of the data. I am just in the process of writing a test suite for this package/script and tacking an issue like this would be a nice payoff for writing all these darn tests 🍡

**Comment by techouse** [comment]
Well unless you're willing to share there's not much I can do except guess. However, now that the test suite is done and pushed to the repo you can test your undisclosed SQLite databas using this command:

```bash
pytest --sqlite-file=/path/to/your/database.sqlite3
```

Make sure to read the [testing](https://github.com/techouse/sqlite3-to-mysql#testing) section in the README on how to set up the testing environment first.
