### ISSUE TITLE
It seems to ignore decimal places

### ISSUE THREAD

**Issue by joancostacosta** [techouse/sqlite3-to-mysql#21]
Processing this SQL:

_CREATE TABLE IF NOT EXISTS "planidiet_app_valornormalperfil" (
	"id"	integer NOT NULL,
	"quantitat"	decimal(9, 5) NOT NULL,
	"calories"	decimal(9, 5) NOT NULL,
	"element_id"	integer NOT NULL,
	"perfil_id"	integer NOT NULL,
	FOREIGN KEY("element_id") REFERENCES "planidiet_app_element"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("perfil_id") REFERENCES "planidiet_app_perfil"("id") DEFERRABLE INITIALLY DEFERRED,
	PRIMARY KEY("id" AUTOINCREMENT)
);_

It creates that table in MySQL:

Table:planidiet_app_valornormalperfil
Columns:
id | int PK
quantitat | decimal(10,0)
calories | decimal(10,0)
element_id | int
perfil_id | int

Seems to ignore decimal digits!!

**Comment by techouse** [comment]
Hey! I'm sorry but I simply can't reproduce this. I've even written a specific test for this and it passes normally.

I tried converting your SQLite DDL

```sql
CREATE TABLE "planidiet_app_valornormalperfil"
(
    "id"         integer       NOT NULL,
    "quantitat"  decimal(9, 5) NOT NULL,
    "calories"   decimal(9, 5) NOT NULL,
    "element_id" integer       NOT NULL,
    "perfil_id"  integer       NOT NULL,
    FOREIGN KEY ("element_id") REFERENCES "planidiet_app_element" ("id") DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY ("perfil_id") REFERENCES "planidiet_app_perfil" ("id") DEFERRABLE INITIALLY DEFERRED,
    PRIMARY KEY ("id" AUTOINCREMENT)
);
```

and it got converted to

```mysql
CREATE TABLE `planidiet_app_valornormalperfil` (
  `id` int NOT NULL,
  `quantitat` decimal(9,5) NOT NULL,
  `calories` decimal(9,5) NOT NULL,
  `element_id` int NOT NULL,
  `perfil_id` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```
