### ISSUE TITLE
Using int() method to a string.

### ISSUE THREAD

**Issue by 669344682** [techouse/sqlite3-to-mysql#24]
```2021-08-01 02:17:29 INFO     Transferring table cdkeys
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 72.55it/s]
2021-08-01 02:17:29 INFO     Transferring table accounts
invalid literal for int() with base 10: b'1 19:27:7'
```
![image](https://user-images.githubusercontent.com/7806033/127749125-dc3b65bc-9dc7-40ba-9215-b81517ef2da1.png)
This is a text value in SQLite database actually, it seems like to int() a string.

**Comment by techouse** [comment]
Hey, and thanks for the bug report.

Could you please use the bug issue template?

Also, this date looks completely invalid, as it's missing the padded zeros. A raw dump of your MySQL database (just a snipped with the problematic data, I don't need to see all your database) would help.
