### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by ad1tya2** [techouse/sqlite3-to-mysql#25]
I get an error called `not enough values to unpack (expected 2, got 1)` While trying to convert,
I can not provide any additional info because thats all it shows, 

```
2021-08-11 10:58:57 INFO     Transferring table global_stats
not enough values to unpack (expected 2, got 1)
```

**Comment by techouse** [comment]
Hi, could you please use the bug report template?

Also, I'll need more info on your table and possibly a snippet of the data you're trying to convert.

**Comment by techouse** [comment]
Closing issue. Feel free to re-open with more info.
