### ISSUE TITLE
Convertion hang on 'no such collation sequence: unicase' leading some tables crunched

### ISSUE THREAD

**Issue by sosie-js** [techouse/sqlite3-to-mysql#28]
**Describe the bug**
Hello techouse, today I wanted to convert fresh and clean anki database .anki2 (sqlite3 based) into mysql to retrieve the schema on phpmysql and work on it. 

I succeed to retrieve the schema (aka ER Diagram) from the fresh sqlite3 database with anki created with:
```bash
anki -l en -b ankidir/
```
using after DBeaver-ce behind on collection.anki2 .
 As you can see collection.anki2, a sqlite3 database contains 12 tables:

![image](https://user-images.githubusercontent.com/70700670/133315762-45ea34f1-0a3f-4eb4-9099-cb8f1b10dc6d.png)

So what I did is to convert to mysql is
1) first create a mysql anki database for the user anki with phpMyAdmin
2) launch the conversion
```bash
sqlite3mysql -f ankidir/User\ 1/collection.anki2 -d anki -u anki -p
```

**Expected behaviour**
All  table conversion Completed

**Actual result**
```bash
sqlite3mysql -f ankidir/User\ 1/collection.anki2 -d anki -u anki -p 
MySQL password: 
2021-09-14 20:36:30 INFO     Transferring table col
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 22.26it/s]
2021-09-14 20:36:31 INFO     Adding index to column "mid" in table notes
2021-09-14 20:36:31 INFO     Adding index to column "csum" in table notes
2021-09-14 20:36:31 INFO     Adding index to column "usn" in table notes
2021-09-14 20:36:32 INFO     Adding index to column "odid" in table cards
2021-09-14 20:36:32 INFO     Adding index to column "did, queue, due" in table cards
2021-09-14 20:36:32 INFO     Adding index to column "nid" in table cards
2021-09-14 20:36:33 INFO     Adding index to column "usn" in table cards
2021-09-14 20:36:34 INFO     Adding index to column "cid" in table revlog
2021-09-14 20:36:34 INFO     Adding index to column "usn" in table revlog
2021-09-14 20:36:34 INFO     Transferring table deck_config
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 21.88it/s]
2021-09-14 20:36:35 INFO     Transferring table config
100%|██████████████████████████████████████████| 15/15 [00:00<00:00, 341.32it/s]
no such collation sequence: unicase
```

**System Information**

```bash
$ sqlite3mysql --version
```

```
| software               | version                                                                                   |
|------------------------|-------------------------------------------------------------------------------------------|
| sqlite3-to-mysql       | 1.4.5                                                                                     |
|                        |                                                                                           |
| Operating System       | Linux 4.19.0-17-amd64                                                                     |
| Python                 | CPython 3.9.5                                                                             |
| MySQL                  | mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 |
| SQLite                 | 3.27.2                                                                                    |
|                        |                                                                                           |
| click                  | 8.0.1                                                                                     |
| mysql-connector-python | 8.0.26                                                                                    |
| pytimeparse            | 1.1.8                                                                                     |
| simplejson             | 3.17.3                                                                                    |
| six                    | 1.16.0                                                                                    |
| tabulate               | 0.8.9                                                                                     |
| tqdm                   | 4.62.1                                                                                    |

```

**Additional context**
If you take a look on phpMyAdmin designer.. you see whose tables has been crunched (5 disappeared) or even renamed in uppercase like fields.

![image](https://user-images.githubusercontent.com/70700670/133319253-8343543c-1cf6-4fb8-8763-7e66f46e07f8.png)

To help you, here is [a zip of ankidir folder](http://sosie.sos-productions.com/gift/ankidir.zip)

**Comment by techouse** [comment]
Could be related to https://github.com/patarapolw/ankisync2/issues/3

**Comment by sosie-js** [comment]
I don't know maybe you need to declare the extension like mentioned, just before the fatal line.

```python3
from unidecode import unidecode

def unicase_compare(x, y):
    x_ = unidecode(x).lower()
    y_ = unidecode(y).lower()
    return 1 if x_ > y_ else -1 if x_ < y_ else 0

connection.create_collation("unicase", unicase_compare)
```

I have not copied your project to patch it, so I don't know where it occurs.

**Comment by sosie-js** [comment]
It's the same, it hangs as well on 'no such collation sequence: unicase' with collation utf8mb4_bin

**Comment by sosie-js** [comment]
Wrong code

**Comment by sosie-js** [comment]
Ok Mr Techouse, I will say, don't bother with it unless you have free time. The way I solved is manually remove de COLLATE unicase stuff and going into manual debug mode with phpMyAdmin to remove buggy incompatible parts, this includes :
```
-UNIQUE KEY Stuff, 
-string keys are not possible like "KEY text NOT NULL PRIMARY KEY,"
-without xxx unsupported such as "without rowid"
-extra tables like "sqlite_stat1 , sqlite_stat4"
-remove extra ANALYZE sqlite_master;
-Records seeing having  duplicate because mulitcolumn agregate key is not supported 
 ie PRIMARY KEY (ntid, ord)
-backslash quoting column names that can not be used because using reserved keywords: mod, KEY, left. field.
-washing all lines "CREATE INDEX foo ON bar ;"
```

**Comment by techouse** [comment]
Thanx for the info @sosie-js :) Much appreciated.

Just to be clear, this tool was never intended to convert just any custom roll-your-own corrupt database. The main purposes of it is to get data across different databases. 
This implies that you make sure that the data you'll be feeding it is not corrupt or malformed (as was the case with this unsupported collation) and that you later make sure that everything is as it should be in MySQL using a DBA tool like DBeaver etc.

**Comment by sosie-js** [comment]
The sqlite3 is not corrupted in our case , it is just that conversion to mysql is not an easy task as people claims using exports, the converter sqlite3-to-mysql.py and then import. As all easy things it should be, pepper and salt like this extra collate can make your life difficult for nothing...

**Comment by techouse** [comment]
Again, this is not a bug, as you describe it. The problem is that Anki's DB uses a custom collation and to handle it one has to implement it manually. I haven't done it (yet) simply because it's fairly uncommon to see something like this and because it's a fringe edge case.

I'll try adding a custom collation handler and see if the tests work.

**Comment by sosie-js** [comment]
We agree each other but you are going to explode the Won't Fix tag ;p

**Comment by techouse** [comment]
Try pulling the latest master branch and test with it. My tests were successful.

**Comment by sosie-js** [comment]
WELL DONE TECHOUSE !

 I have first to uninstall sqlite3tomysql 
```bash
sudo pip3 uninstall sqlite3-to-mysql

install from repos
```bash
git clone https://github.com/techouse/sqlite3-to-mysql
cd sqlite3-to-mysql
sudo python3 setup.py install
```
an then
```bash
sqlite3mysql -f ankidir/User\ 1/collection.anki2 -d anki -u anki -pMySQL password: 
```
and the winner is...sorry there is still a bad duck the yellow one as in uppercase
![image](https://user-images.githubusercontent.com/70700670/133501317-ff1c45da-83b6-4c79-9063-11ee9a07a9b2.png)

Since I exoprted the diagram in dia, commented the fields in phpMyAdmin according to the [Database Structure ](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure)
![image](https://user-images.githubusercontent.com/70700670/133502805-9ed3b57d-2b83-4eb7-9f57-8ed01586fab9.png)

**Comment by techouse** [comment]
I'm not entirely sure what you mean? Should the `FIELDS` table be an all-lowercase `fields`? But if you check the dump that you gave me, it's all uppercase.

<img width="704" alt="Screenshot 2021-09-15 at 21 23 32" src="https://user-images.githubusercontent.com/1174328/133504647-1f932ee2-8f52-43f1-bbdf-064601c9b21d.png">

<img width="737" alt="Screenshot 2021-09-15 at 21 23 42" src="https://user-images.githubusercontent.com/1174328/133504661-cdab1482-20ae-4cfa-a8a3-dd5d2db579eb.png">
 
<img width="759" alt="Screenshot 2021-09-15 at 21 25 01" src="https://user-images.githubusercontent.com/1174328/133504682-bf7824c3-017b-4742-abf9-8d1d666f6797.png">

**Comment by sosie-js** [comment]
Well I am sorry it is indeed FIELDS with `sqlite3 collection.anki .dump`.
No bad duck, it's good luck. You win the [bunny gold prize](http://sosie.sos-productions.com/gift/)
Big thanks. SoSie

**Comment by techouse** [comment]
Cool, I'll probably make PyPI a release over the weekend.

**Comment by techouse** [comment]
@sosie-js you can grab [v1.4.6](https://pypi.org/project/sqlite3-to-mysql/) from PyPI now using your regular `pip install` 🚀

**Comment by sosie-js** [comment]
I confirm you blew up the tag 'Wont Fix' now \o/
```
sudo pip3 uninstall sqlite3-to-mysql
sudo pip3 install sqlite3-to-mysql
Successfully installed sqlite3-to-mysql-1.4.6

I made shell script: ankisqlite3toMYSQL.sh from ou dicussion and I confirm the twelve tables generated from mysql side. I seen sqlit3 did not support comments embedded in columns, with sqlit3 tool, they are not lost. I am not sure you magic tool handle them however as it seems you are a fan of anki.. the missing puzzle is the JSONObject diagram:

![Anki2 1JSONObjects](https://user-images.githubusercontent.com/70700670/133928049-27a5ba2c-0948-4021-b86e-0eef14893acf.png)

Hey the bunny is playing with anki and dia API now ^_^
