### ISSUE TITLE
The Boolean type is not converted to int, but to varchar

### ISSUE THREAD

**Issue by zhangzimao** [techouse/sqlite3-to-mysql#31]
**Describe the bug**

**Expected behaviour**
What you expected.

**Actual result**
What happened instead.

**System Information**

```bash
$ sqlite3mysql --version
```

```
<paste here>
```

This command is only available on v1.3.6 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

**Comment by techouse** [comment]
I will need some more info here. Can you please fill out the bug report theme above and provide a database sample?
