### ISSUE TITLE
Sqlite to MySQL keeping datetime

### ISSUE THREAD

**Issue by jbeuria** [techouse/sqlite3-to-mysql#32]
**Is your feature request related to a problem? Please describe.**
When it parses datetime in sqlite, it gives null entries in mysql db

**Describe the solution you'd like**
No idea

**Describe alternatives you've considered**
not considered

**Additional context**

**Comment by techouse** [comment]
Hi,

Can you please elaborate a bit more please?

**Comment by jbeuria** [comment]
I have a sqlite table, say

CREATE TABLE books (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name text NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP
);
insert into books (1, 'Sample Name', 1637995103544)

Now when I convert it to mysql, I see the timestamp is shown as **0000-00-00 00:00:00**
![image](https://user-images.githubusercontent.com/57653501/149127983-edeb475a-86bf-471c-848a-4567e91733e1.png)

Could you please suggest how to do this. The actual table has thousands of entries. I have just given a prototype. 

[test.db.zip](https://github.com/techouse/sqlite3-to-mysql/files/7854022/test.db.zip)

**Comment by techouse** [comment]
The 1st problem might be that you're using milliseconds rather than seconds, the second one is that your datetime is in seconds rather than in an ISO format. I suggest you clean up your data before doing the transfer.
