### ISSUE TITLE
sqlite to MS SQL

### ISSUE THREAD

**Issue by madansu** [techouse/sqlite3-to-mysql#33]
Hi,

Is there any way the script can be adapted for pushing the data into MS SQL, instead of mysql ?

Thanks in advance !

**Comment by techouse** [comment]
Hi. 

No, that's not possible and not planned.

Your best bet is converting your SQLite to MySQL and then following [this migration guide](https://docs.microsoft.com/en-us/sql/sql-server/migrate/guides/mysql-to-sql-server).
