### ISSUE TITLE
mysql-string-type argument has no effect

### ISSUE THREAD

**Issue by yonglezhu** [techouse/sqlite3-to-mysql#34]
I want to set mysql-string-type argument to MEDIUMTEXT,but has no effect,string values from sqlite always convert to TEXT type

version 1.4.8，1.4.9 both have this issue

**Comment by techouse** [comment]
Hey!

Thanks for the bug report. I only factored in `TEXT` and completely forgot about `MEDIUMTEXT` and `LONGTEXT`.

I'll fix it ASAP.

**Comment by techouse** [comment]
I added this parameter now to specifically address TEXT (rather than strings)

```
--mysql-text-type [TINYTEXT|MEDIUMTEXT|TEXT|LONGTEXT]
                                  MySQL default text field type. Defaults to
                                  TEXT.
```

**Comment by yonglezhu** [comment]
> I added this parameter now to specifically address `TEXT` (rather than strings)
> 
> ```
> --mysql-text-type [TINYTEXT|MEDIUMTEXT|TEXT|LONGTEXT]
>                                   MySQL default text field type. Defaults to
>                                   TEXT.
> ```

Greate！
