### ISSUE TITLE
Problem with datetime

### ISSUE THREAD

**Issue by hofaa** [techouse/sqlite3-to-mysql#4]
Hey there, thanks for this awesome project, it's the only one I could find that really works well.
Unfortunately I'm experiencing problems with my database. My sqlite values of type datetime have all been converted to 0000-00-00 00:00 (also type datetime in MySQL)

Also autoincrement flag has not been transferred to MySQL (which is easy to fix for my table though)

Can somebody support please? Do you need more information?

Cheers
Hofaa

**Comment by techouse** [comment]
Hmm can you maybe provide me with some randomized set of the SQLite database if it's not too big of a secret?

**Comment by hofaa** [comment]
Wouldnt post it here but I sent you it via mail

**Comment by techouse** [comment]
Well from what I can tell just by looking at the data you have your time defined as a `datetime` SQLite column but the time is in a UNIX timestamp integer opposed to being in an actual string-representation of `YYYY-MM-DD HH:mm:ss`.

Hmm, that's gonna be a tough one to crack. 

You should probably not have the SQLite column defined as `datetime` but as `numeric`. That way the tool will transfer it as an integer to MySQL. Then you can do some transformation of the data to represent it as actual datetime.

**Comment by hofaa** [comment]
Thank you very much for this, that did the trick! Great tool!
