### ISSUE TITLE
how to ignore  index

### ISSUE THREAD

**Issue by zeroone2005** [techouse/sqlite3-to-mysql#48]
sqlite3 index field is text ,convert to mysql get an error :   MySQL failed adding index to column "sorting" in table ay_content: 1089 (HY000): Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys

**Comment by techouse** [comment]
Hi. I will need more info.

In general using a string index is not recommended, because it has to be truncated to a maximum length.

Please attach your database's DDL with some example data which can reproduce the error.
