### ISSUE TITLE
just convert to a MySQL-compatible dump to stdout

### ISSUE THREAD

**Issue by drzraf** [techouse/sqlite3-to-mysql#49]
**Is your feature request related to a problem? Please describe.**
Contrary to SO scripts, this script tries to do the import. But in some case it's preferible to just get the MySQL-compliant output because MySQL is down / on another machine, ... or additional post-processing is needed, ...

**Describe the solution you'd like**
Don't make MySQL credentials/connection mandatory and output the convert dump to stdout.

**Comment by techouse** [comment]
In this case, I simply suggest using a local MySQL database as the target and then exporting the SQL dump from there.
