### ISSUE TITLE
sqlite3mysql

### ISSUE THREAD

**Issue by martinjeaks** [techouse/sqlite3-to-mysql#53]
sqlite3mysql converts sqlite3 tables to mysql tables by giving "sqlite3mysql -f e:/mydata.db -d mydata -uroot -p". It converts few tables and stopes with an error "Invalid column_type!". But it does not show which table has the problem.

**Comment by techouse** [comment]
Hi @martinjeaks 

Try and run it with `--debug`. That will throw exceptions and let you know what's wrong.
