### ISSUE TITLE
Correct Transfer of Nullable Primary Keys

### ISSUE THREAD

**Issue by FireController1847** [techouse/sqlite3-to-mysql#6]
Hello! I am absolutely loving this package and thank you for the effort and work you've put into it :)

I noticed while trying to transfer one of my databases, that SQLite allows for null values in the primary key column, whereas MySQL doesn't. What I've noticed is that when I go to transfer an SQLite3 database to MySQL using this, it will crash when making the table because of this.

I just wanted to bring this to your attention, in hopes that you'd be willing to fix it :)

**Comment by techouse** [comment]
Cool, thanx. Another edge case that escaped me :)
