### ISSUE TITLE
Slow while transfering large tables

### ISSUE THREAD

**Issue by DoctorAti** [techouse/sqlite3-to-mysql#74]
**Describe the bug**
For tables with like more than 10,000 rows. Why it takes so kuch time. 
command i ran:
sqlite3mysql -f student_club.sqlite  -d student_club -u ..  -h ..-p -E -c 1000

**Expected behaviour**
While using tools like dbeaver its just matter of few seconds to transfer 10,000 rows.

**Actual result**
For transfering 1000 rows it is taking 500 seconds

**System Information**

  sqlite3mysql --version

| software               | version                                                                |
|------------------------|------------------------------------------------------------------------|
| sqlite3-to-mysql       | 2.0.2                                                                  |
|                        |                                                                        |
| Operating System       | Darwin 21.3.0                                                          |
| Python                 | CPython 3.9.16                                                         |
| MySQL                  | mysql  Ver 8.0.28 for macos11 on x86_64 (MySQL Community Server - GPL) |
| SQLite                 | 3.42.0                                                                 |
|                        |                                                                        |
| click                  | 8.1.3                                                                  |
| mysql-connector-python | 8.0.33                                                                 |
| pytimeparse2           | 1.7.1                                                                  |
| simplejson             | 3.19.1                                                                 |
| tabulate               | 0.9.0                                                                  |
| tqdm                   | 4.65.0                                                                 |
```

**Additional context**
Add any other context about the problem here.

**Comment by DoctorAti** [comment]
it was host issue, when i tried with localhost , it is running fast.

**Comment by techouse** [comment]
Hey 👋 

Glad you managed to sort this out by yourself.

Just out of curiosity, you tried connecting to an online host?
