### ISSUE TITLE
After migration and post-migration

### ISSUE THREAD

**Issue by lakusz1github** [techouse/sqlite3-to-mysql#81]
After Post-Migration step, should I Service Recorder set Enable ?

Explanation:
First step is
Maria DB Migration Steps
    1. Stop the recorder service from developer tools
( ‘Developer Tools’ > ‘Services’ > Search for Recorder: Disable > Press the ‘Call service’ ) 

But after migration Recorder Service is not Enabled, question is should me ?

**Comment by techouse** [comment]
Hi. I'm sorry, but I still don't understand. Please elaborate.

**Comment by lakusz1github** [comment]
If i set Service "Recorder" to Disable, then after migration no data will be recorded right ?

**Comment by techouse** [comment]
I really have no idea what you're talking about. This package does not do any recording. I'll close this issue as there's obviously been some sort of mixup here.

**Comment by lakusz1github** [comment]
What is not clear for you ? but who cares ....
