### ISSUE TITLE
sqlite3mysql: command not found ubuntu 22.04 installation or usage issue

### ISSUE THREAD

**Issue by thenik** [techouse/sqlite3-to-mysql#84]
ubuntu 22.04 installation or usage issue , I installed using the next cmd
`python3 -m pip install sqlite3-to-mysql`

![image](https://github.com/techouse/sqlite3-to-mysql/assets/1731242/2c2c4a99-578a-4856-bdc3-cd12e2b92d26)
looks installation was ok , and there is no any error here.

But When I run cmd  
`sqlite3mysql --help`
or 
`python3  sqlite3mysql --help`
I got results sqlite3mysql: command not found
![image](https://github.com/techouse/sqlite3-to-mysql/assets/1731242/39a8992a-f6f9-47fd-bf08-267f23fde6aa)

update:
I found the script here 

![image](https://github.com/techouse/sqlite3-to-mysql/assets/1731242/c88cfd56-ce23-4c8a-a965-2f15492f9957)

**Comment by techouse** [comment]
Hey. I suggest you check you path. Alternatively, you should make a local environment and install it into it.

Check this tutorial here https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/
