### ISSUE TITLE
sqlite3mysql is not defined

### ISSUE THREAD

**Issue by hawajka76** [techouse/sqlite3-to-mysql#88]
Hello, I've installed as per the readme however when I run  sqlite3mysql I get a 'sqlite3mysql' is not defined error. 
I've tried importing via the following commands
import sqlite3_to_mysql
from sqlite3_to_mysql import mysql_utils
from sqlite3_to_mysql import sqlite_utils
from sqlite3_to_mysql.transporter import SQLite3toMySQL
from sqlite3_to_mysql import click_utils
from sqlite3_to_mysql import cli

sqlite3mysql is not defined regardless of what I import

I'm running Python 3.8 and running version 2.0.3. How can I make this work?

**Comment by hawajka76** [comment]
Quick update, it works if I open directly in the directory ~/.local/bin. 
According to print(sys.path) this directory is being already scanned. Do you have any ideas why I can't I use the script without moving to ~/.local/bin?

**Comment by techouse** [comment]
Hey!

I'm not sure what you're trying to achieve by importing it.

If you want to use it as a library inside another script, the  I suggest you make a python virtual environment, activate it and install it there.

**Comment by hawajka76** [comment]
It was not detected so I was confused about whether I should import it. It only worked when I opened it in the ~/.local/bin directory.

**Comment by techouse** [comment]
Sounds to me like your path is messed up because you installed a python package weirdly. Do this:

1. create a virtual environment
2. activate the virtual environment
3. pip install it into that virtual environment
