### ISSUE TITLE
sqlite3-to-mysql privat problem

### ISSUE THREAD

**Issue by JoeGhost-22** [techouse/sqlite3-to-mysql#89]
I'm very sorry, if not allowed, please delete.
I can't find help, so I thought I try it here. 
I#m a absolut beginner and not compfortable with other OS's like windows. So all the commands and syntaxes are totaly new and I can't learn as fast as I should.
I tried to migrate my sqlite3 db from ha to mysql. mysql and phpmyadmin are installed and working.
I found a 'script' to install that sqlite3-to-mysql and tried it.
apk add python3
apk add py3-pip
pip3 install sqlite3-to-mysql
the first and second command were executed, successfull.
But the third command aborts with an error message and that is where I need help.
![sqlite3 install error](https://github.com/techouse/sqlite3-to-mysql/assets/113529386/f92dd275-b9d6-44c6-9e5f-1bed7e3cf337)

what can I do to make it work?
Please help me cause I dont know how and what to do.

thank you
Joerg

**Comment by techouse** [comment]
Make a virtual environment and install it there. Read more here https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by JoeGhost-22** [comment]
thank you, I'll try it, but it looks very difficult for me.
If it dosent work I'll loose my history ...

**Comment by JoeGhost-22** [comment]
Thank you very much.
I don't know how, but I got it. 
The migration is done successfull.
best regards
Joerg
