### ISSUE TITLE
1427 (42000) error when Transferring table

### ISSUE THREAD

**Issue by landws** [techouse/sqlite3-to-mysql#93]
2023-11-11 18:09:10 INFO     Transferring table STKS
100%|██████████████████████████████████████████████████| 2570/2570 [00:28<00:00, 90.92it/s]
2023-11-11 18:09:39 ERROR    MySQL failed creating table MYSTKS: 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'C2').
1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'C2').
(base) PS C:\WINDOWS\system32> sqlite3mysql --version
| software               | version                              |
|------------------------|--------------------------------------|
| sqlite3-to-mysql       | 2.1.1                                |
|                        |                                      |
| Operating System       | Windows 10                           |
| Python                 | CPython 3.8.8                        |
| MySQL                  | MySQL client not found on the system |
| SQLite                 | 3.35.4                               |
|                        |                                      |
| click                  | 8.1.7                                |
| mysql-connector-python | 8.2.0                                |
| pytimeparse2           | 1.7.1                                |
| simplejson             | 3.19.2                               |
| tabulate               | 0.8.9                                |
| tqdm                   | 4.66.1                               |

and the table & data rows in target schema(mysql)

select count(*) from stks --- return 2570 rows

thanks

**Comment by techouse** [comment]
Hi,

Can you please elaborate what the issue is and make the bug report less cryptic.

From what I can see it complains that the data is somehow invalid.

A SQLite dump would greatly help shedding a light onto the matter.

**Comment by landws** [comment]
Hi,

the table STKS dump is too big, if the DDL can provide some helps

CREATE TABLE [STKS] (
  [CO] [CHAR(12)], 
  [C1] INTEGER, 
  [C2] [CHAR(6)], 
  [C3] INTEGER, 
  [C4] [CHAR(6)], 
  [C5] [CHAR(36)], 
  [C6] INTEGER, 
  [C7] INTEGER, 
  [C8] INTEGER, 
  [C9] INTEGER, 
  [C10] [CHAR(3)], 
  [C11] [CHAR(12)], 
  [C12] [CHAR(7)], 
  [C13] FLOAT, 
  [C14] [CHAR(50)], 
  [C15] [CHAR(50)], 
  [C16] INTEGER, 
  [C17] INTEGER, 
  [C18] [CHAR(1)], 
  [C19] [CHAR(16)], 
  [C20] INTEGER, 
  [C21] [CHAR(8)], 
  [C22] INTEGER, 
  [C23] [CHAR(4)], 
  [C24] [CHAR(8)], 
  [C25] [CHAR(13)], 
  [C26] [CHAR(50)], 
  [C27] [CHAR(50)], 
  [C28] INTEGER, 
  [C29] [CHAR(8)], 
  [C30] INTEGER, 
  [C31] INTEGER, 
  [C32] INTEGER, 
  [C33] [CHAR(50)]);

thanks.

**Comment by techouse** [comment]
Hey,

Sorry, that doesn't help at all, I'm afraid. The problem is with your data.

The error points to column `C2` which in your DDL is listed as `CHAR(6)` but for some reason it is treated as a `float` or `decimal`.

At least try to provide a few rows of `C2` so that we can get an idea of what's going on.

**Comment by landws** [comment]
Hi,

sorry, column C2 value is CNSESH or CNSESZ, like...

rowid	CO	C1	C2	C3	C4	C5	C6	C7	C8	C9	C10	C11	C12	C13	C14	C15	C16	C17	C18	C19	C20	C21	C22	C23	C24	C25	C26	C27	C28	C29	C30	C31	C32	C33
1	SH600000.stk	19991110	CNSESH	10000001	浦发银行	PU DEV BANK	1	101	2	1	CNY	CNE0000011B7	6182043	29.5			0	1	J	金融业	40	金融	440000	金融服务	06010101	综合性银行			310000	上海市	0	947	1	PFYH
2	SH600004.stk	20030428	CNSESH	10001272	白云机场	BAIYUN AIRPORT	1	101	2	1	CNY	CNE000001DX0	6610221	7.72			0	1	G	交通运输、仓储和邮政业	20	工业	420000	交通运输	02030501	机场服务			440000	广东省	0	951	1	BYJC

and, with --debug cmd runs out result

023-11-11 20:14:36 ERROR    MySQL failed creating table MYSTKS: 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'C2').
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\sqlite3mysql.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlite3_to_mysql\cli.py", line 153, in cli
    SQLite3toMySQL(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlite3_to_mysql\transporter.py", line 651, in transfer
    self._create_table(table["name"], transfer_rowid=transfer_rowid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlite3_to_mysql\transporter.py", line 368, in _create_table
    self._mysql_cur.execute(sql)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\cursor.py", line 1356, in execute
    self._prepared = self._connection.cmd_stmt_prepare(operation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\connection.py", line 1367, in cmd_stmt_prepare
    result = self._handle_binary_ok(packet)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mysql\connector\connection.py", line 1303, in _handle_binary_ok
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'C2').

thanks.

**Comment by techouse** [comment]
Hey,

Sorry, I still can't help you much here, as I'm, not sure why it would want to convert a string to a decimal.

Looks like you'll have to do the detective work yourself.

**Comment by landws** [comment]
Hi,

sorry, I found the error is not about table STKS, It failed on creating table MYSTKS.

ERROR MySQL failed creating table MYSTKS: 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'C2').

it's occurring after table STKS created and transferred...

here is the DDL of table MYSTKS and few rows of data

CREATE TABLE [MYSTKS] (
  [CO] CHAR NOT NULL, 
  [C1] BIGINT NOT NULL, 
  [C2] [DECIMAL(0, 2)], 
  CONSTRAINT [] PRIMARY KEY ([CO] COLLATE NOCASE ASC));

rowid	CO	C1	C2
2	600196.SS	20130929	13.78
3	002019.SZ	20130929	18.1
6	002024.SZ	20130929	11.68

thanks.

**Comment by techouse** [comment]
> [C2] [DECIMAL(0, 2)],

There's your error. This is an invalid `DECIMAL` declaration. And just like the error says

> M must be >= D (column 'C2')

It would have to be `DECIMAL(2,2)` or something within those lines.

Read more here on `DECIMAL` https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html

**Comment by landws** [comment]
Yes. cool, thanks for your help.
