### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by the-hotmann** [techouse/sqlite3-to-mysql#96]
I spun up the newest python3 docker-container:
`docker run -it --rm python:latest bash`

and executed this:

```
python3 -m venv .venv && source .venv/bin/activate && \
pip install --upgrade pip && \
pip install sqlite3-to-mysql && \
sqlite3mysql --help
```

(according to the docs)

But actually this was not enough to make the package work.
I also needed to install `packaging` to make it work. Maybe add this as a dependency, or add to the docs, that this must be installed.

Anyway my start-script now looks like this:

```
mkdir /TEMP && cd /TEMP && \
python3 -m venv .venv && source .venv/bin/activate && \
pip install --upgrade pip && \
pip install sqlite3-to-mysql packaging && \
sqlite3mysql --help
```

and is working.
Hope this helps improving the application.

**Comment by techouse** [comment]
Thanks for the bug report!

Fixed in v2.1.3.
